services:
  progressapi:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: always
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge